http:
  routers:
    api:
      rule: 'Host(`api.shop.localhost`) || ((Host(`shop.localhost`) || Host(`admin.shop.localhost`)) && PathPrefix(`/api/`))'
      service: api
      priority: 100
      entryPoints: [web]
    admin:
      rule: 'Host(`admin.shop.localhost`)'
      service: admin
      priority: 10
      entryPoints: [web]
    web:
      rule: 'Host(`shop.localhost`)'
      service: web
      priority: 10
      entryPoints: [web]
  services:
    api:
      loadBalancer:
        servers: [{ url: 'http://host.docker.internal:4000' }]
    admin:
      loadBalancer:
        servers: [{ url: 'http://host.docker.internal:3001' }]
    web:
      loadBalancer:
        servers: [{ url: 'http://host.docker.internal:3000' }]
